### ISSUE TITLE
[Idea] Forbid multiple statements on migrations that have disable_ddl_transaction!

### ISSUE THREAD

**Issue by fsateler** [ankane/strong_migrations#125]
Hi,

Thanks for this cool gem.

I'd like to propose a new check. I have no idea if it is feasible:

- Forbid multiple statements on migrations that have `disable_ddl_transaction!`

Because the transaction is disabled, should the migration fail in any but the first operation, then the migration would be partially applied.

This makes recovery difficult, since one then needs to manually edit the migration. The problem is compounded if one is using multitenancy in the vein of the apartment gem.

Therefore, when DDL transactions are disabled, a migration is only safe if it is either a single statement, or idempotent.

**Comment by ankane** [comment]
Hey @fsateler, it's an interesting idea for a best practice. As far as I know, there's not a way to see how many statements will be executed ahead of time. You could raise an error when a 2nd statement is detected in the dev/test environments, but since the first will have already run, it'll leave the database in an inconsistent state on that specific machine (but will likely prevent it from making it to production).

It's probably not something I'd want to add to the gem right now, but if you decide to fork and try it, let me know how it goes.
