### ISSUE TITLE
Explain two separate deployments when removing a column

### ISSUE THREAD

**Issue by alexeyr-ci1** [ankane/strong_migrations#208]
The ["Good" alternative for removing a column](https://github.com/ankane/strong_migrations#good) suggests two separate deployments. But I don't see why deploying
```
class User < ApplicationRecord
  self.ignored_columns = ["name"]
end

class RemoveColumn < ActiveRecord::Migration[7.0]
  def change
    safety_assured { remove_column :users, :name }
  end
end
```
in a single commit wouldn't work. Can you add an explanation?

**Comment by alexeyr-ci1** [comment]
After thinking some more: is the explanation that `rake db:migrate` will run before the final code is deployed, so if both are done in a single deploy: 
1. there is a narrow window after `db:migrate` where old code is still running and can access the removed column;
2. the deploy can fail, but the migration won't be rolled back by default, so again we can end up with old code trying to access the removed column?

**Comment by ankane** [comment]
A single commit should be fine if you wait until all the old code is no longer running to run the migration.

**Comment by alexeyr-ci1** [comment]
Thank you!

**Comment by diazruy** [comment]
Follow up question: why is a _third_ deploy (for step 5) necessary? Wouldn't it be ok to do it (remove the `ignored_columns=`) in the same deploy that has the migration to `remove_column` (step 3/4)? By this point, due to the previous deploy, all instances should already be ignoring the column and after the removal, on boot, the cache would no longer detect the new column and thus the `ignored_columns` would be unnecessary, would it not?

**Comment by ankane** [comment]
If you can guarantee the column is removed before the app boots, that'll work (for instance, you run migrations before the app is deployed to application servers).

**Comment by diazruy** [comment]
Thanks for the quick reply! 

So, in the case of heroku, where we're running migrations as part of the `release` phase, this would be the case, since the web servers are not actually restarted (with the new code) until after successful completion of `release`.
